[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static", "-Ctarget-cpu=native"]

[target.aarch64-apple-darwin]
rustflags = ["-Ctarget-feature=+crt-static", "-Ctarget-cpu=native"]

[env]
ORT_LIB_LOCATION = "./lib"
